"use client";

import { useState } from "react";
import { useTranslations } from "next-intl";
import { Bot, Copy, Check } from "lucide-react";
import { Button } from "@/components/ui/button";

interface PhaseInfo {
  phase: number;
  key: string;
  title: string;
}

interface GDDAIPromptExportProps {
  title: string;
  gddData: Record<string, Record<string, unknown>>;
  isCompleted: boolean;
  phases: PhaseInfo[];
}

function generateAIPrompt(title: string, data: Record<string, Record<string, unknown>>, phases: PhaseInfo[]): string {
  const pitch = data.pitch || {};
  const engine = (pitch.game_engine as string) || "Unknown";
  const platform = (pitch.platform as string) || "Unknown";
  const concept = (pitch.concept as string) || title;

  const lines: string[] = [];
  lines.push(`# AI Development Assistant Prompt`);
  lines.push(`## ${title}`);
  lines.push("");
  lines.push(`You are an AI coding assistant helping to develop a game. Below is the complete Game Design Document (GDD) that defines all aspects of the game. Use this as your primary reference when writing code, making architecture decisions, and implementing features.`);
  lines.push("");
  lines.push(`## Technical Context`);
  lines.push(`- **Game Engine:** ${engine}`);
  lines.push(`- **Platform:** ${platform}`);
  lines.push(`- **Concept:** ${concept}`);
  lines.push("");

  // Add all GDD sections
  for (const { key, title: phaseTitle } of phases) {
    const phaseData = data[key];
    if (!phaseData || Object.keys(phaseData).length === 0) continue;

    lines.push(`## ${phaseTitle}`);
    lines.push("");

    for (const [field, value] of Object.entries(phaseData)) {
      if (value === null || value === undefined) continue;
      const label = field.replace(/_/g, " ").replace(/\b\w/g, c => c.toUpperCase());

      if (typeof value === "string") {
        lines.push(`**${label}:** ${value}`);
      } else if (Array.isArray(value)) {
        lines.push(`**${label}:**`);
        if (value.length > 0 && typeof value[0] === "object") {
          value.forEach(v => {
            const name = (v as Record<string, unknown>).name || (v as Record<string, unknown>).title || "Item";
            const desc = (v as Record<string, unknown>).description || "";
            lines.push(`- **${name}**: ${desc}`);
          });
        } else {
          value.forEach(v => lines.push(`- ${String(v)}`));
        }
      } else if (typeof value === "object") {
        lines.push(`**${label}:**`);
        for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
          lines.push(`- ${k}: ${String(v)}`);
        }
      }
      lines.push("");
    }
    lines.push("---");
    lines.push("");
  }

  lines.push(`## Instructions for AI Assistant`);
  lines.push("");
  lines.push(`When working on this project:`);
  lines.push(`1. Always refer back to this GDD when making implementation decisions`);
  lines.push(`2. Maintain consistency with the defined art style, tone, and game mechanics`);
  lines.push(`3. Prioritize features listed in "Core Features" for MVP scope`);
  lines.push(`4. Flag any implementation that deviates from the GDD specifications`);
  lines.push(`5. Use ${engine}-specific best practices and patterns`);
  lines.push(`6. Keep the target platform (${platform}) constraints in mind`);
  lines.push("");
  lines.push(`*Generated by GameLens GDD Creator*`);

  return lines.join("\n");
}

export function GDDAIPromptExport({ title, gddData, isCompleted, phases }: GDDAIPromptExportProps) {
  const [copied, setCopied] = useState(false);
  const t = useTranslations("gdd");

  // Only show when AI assistant is used and GDD is completed
  const meta = gddData._meta as Record<string, unknown> | undefined;
  const usesAI = meta?.uses_ai_assistant === true ||
    (gddData.pitch && (gddData.pitch as Record<string, unknown>).uses_ai_assistant === true);

  if (!usesAI || !isCompleted) return null;

  const handleCopy = async () => {
    const prompt = generateAIPrompt(title, gddData, phases);
    await navigator.clipboard.writeText(prompt);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const prompt = generateAIPrompt(title, gddData, phases);
    const blob = new Blob([prompt], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${title.replace(/[^a-zA-Z0-9]/g, "_")}_AI_Prompt.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex items-center gap-1">
      <Button
        variant="outline"
        size="sm"
        onClick={handleCopy}
        title={t("aiPromptDescription")}
      >
        {copied ? (
          <Check className="h-4 w-4 mr-1 text-green-500" />
        ) : (
          <Copy className="h-4 w-4 mr-1" />
        )}
        {copied ? t("copied") : t("exportAiPrompt")}
      </Button>
      <Button
        variant="ghost"
        size="icon"
        className="h-8 w-8"
        onClick={handleDownload}
        title={t("aiPromptDescription")}
      >
        <Bot className="h-4 w-4" />
      </Button>
    </div>
  );
}
