import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { db } from "@/lib/db";
import { games, analyses, aiAnalyses } from "@/lib/db/schema";

export async function POST() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorized — giriş yap önce" }, { status: 401 });
  }

  const seedGames = [
    {
      userId: user.id,
      title: "Clash Royale",
      studio: "Supercell",
      genre: ["strategy", "card", "moba"],
      platform: "both" as const,
      status: "completed" as const,
      overallRating: "8.5",
      isTemplate: true,
    },
    {
      userId: user.id,
      title: "Royal Match",
      studio: "Dream Games",
      genre: ["match3", "puzzle", "casual"],
      platform: "both" as const,
      status: "playing" as const,
      overallRating: "7.8",
      isTemplate: true,
    },
    {
      userId: user.id,
      title: "PUBG Mobile",
      studio: "Tencent Games",
      genre: ["battle_royale", "shooter"],
      platform: "both" as const,
      status: "completed" as const,
      overallRating: "7.2",
      isTemplate: true,
    },
    {
      userId: user.id,
      title: "Idle Heroes",
      studio: "DH Games",
      genre: ["idle", "rpg"],
      platform: "both" as const,
      status: "dropped" as const,
      overallRating: "5.5",
      isTemplate: true,
    },
    {
      userId: user.id,
      title: "Monopoly GO!",
      studio: "Scopely",
      genre: ["casual", "social_casino"],
      platform: "both" as const,
      status: "playing" as const,
      overallRating: "6.9",
      isTemplate: true,
    },
  ];

  const inserted = await db.insert(games).values(seedGames).returning();

  // Template analyses for first 3 games
  const templateAnalyses = [
    {
      gameId: inserted[0].id, // Clash Royale
      userId: user.id,
      ftueFirstImpression: "Oyun hızlıca tutorial ile başlıyor. İlk maç yapay zekaya karşı, oyuncu temel mekanikleri öğreniyor.",
      ftueOnboardingType: "Interactive tutorial — adım adım kart yerleştirme ve savaş mekaniği öğretiliyor",
      ftueDuration: "3-5 dakika",
      ftueFrictionPoints: "İlk birkaç maçta kart çeşitliliği az, bu hayal kırıklığı yaratabilir",
      ftueRating: "8",
      ftueNotes: "FTUE oldukça başarılı. Oyuncu hemen aksiyon görüyor, uzun metin duvarları yok. Tutorial maçı kaybedilemez tasarlanmış, bu güven veriyor.",
      coreLoopDefinition: "Kart toplama → deck oluşturma → 1v1 gerçek zamanlı savaş → kupa kazanma → sandık açma → yeni kartlar",
      coreLoopSessionLength: "3-5 dakika (tek maç)",
      coreLoopMasteryCurve: "Öğrenmesi kolay, ustalaşması zor. Elixir yönetimi ve kart sayma derin strateji gerektiriyor.",
      coreLoopVariety: "8 kartlık deck sınırı yaratıcılığı zorunlu kılıyor. Meta sürekli değişiyor.",
      coreLoopRating: "9",
      coreLoopNotes: "Core loop mükemmel tasarlanmış. Kısa maçlar yüksek replay value sağlıyor. Gerçek zamanlı PvP heyecan katıyor.",
      monetizationModel: "Freemium — IAP + Battle Pass (Gold Pass)",
      monetizationIap: "Gem paketleri, özel teklifler, arena değeri paketleri",
      monetizationAds: "Reklam yok — tamamen IAP odaklı",
      monetizationBattlePass: "Gold Pass: aylık premium ödüller, chest hızlandırma, özel emote",
      monetizationRating: "7",
      monetizationNotes: "Monetization agresif değil ama pay-to-progress unsuru var. Kart seviyeleri yükseldikçe F2P oyuncular dezavantajlı.",
      retentionRewards: "Günlük sandıklar, savaş ödülleri, klan savaşı ödülleri",
      retentionStreak: "Günlük görevler ve haftalık yarışmalar",
      retentionRating: "8",
      retentionNotes: "Klan sistemi sosyal bağ oluşturuyor. Ladder sistemi sürekli ilerleme hissi veriyor. Sezonluk resetler geri dönüş motivasyonu sağlıyor.",
      uxRating: "8",
      uxNotes: "UI temiz ve responsive. Kart bilgileri kolayca erişilebilir. Battle UI sade ama etkili.",
      metaSystems: "Klan savaşları, turnuvalar, sezonluk ligi, kart koleksiyonu, yıldız seviyeleri",
      metaRating: "9",
      metaNotes: "Meta sistemler çok katmanlı ve derinlik katıyor. Klan sistemi sosyal mekaniklerin en iyilerinden.",
      techRating: "8",
      overallBestFeature: "Gerçek zamanlı 1v1 PvP ve kısa maç süreleri",
      overallWorstFeature: "Kart seviye farkının rekabetçi dengeyi bozması",
      overallUniqueMechanic: "Gerçek zamanlı kart tabanlı strateji — lane-based tower defense hybrid",
      overallTargetAudience: "Kompetitif oyuncular, strateji severler, 16-35 yaş",
      overallLearnings: "Kısa oturum + derin strateji kombinasyonu mobilde çok etkili. Sosyal mekanikler (klan) retention için kritik.",
    },
    {
      gameId: inserted[1].id, // Royal Match
      userId: user.id,
      ftueFirstImpression: "Renkli, sıcak ve davetkar bir açılış. Kral karakteri anında sempati uyandırıyor.",
      ftueOnboardingType: "Guided puzzle — ilk 5 seviye mekanik öğretiyor",
      ftueDuration: "2-3 dakika",
      ftueRating: "9",
      ftueNotes: "FTUE çok akıcı. Oyuncu hiç zorlanmadan temel eşleme mekaniğini öğreniyor. Dekorasyon sistemi hemen tanıtılıyor.",
      coreLoopDefinition: "Puzzle çöz → yıldız kazan → krallığı dekore et → yeni alan aç → puzzle çöz",
      coreLoopSessionLength: "5-15 dakika",
      coreLoopRating: "8",
      coreLoopNotes: "Match-3 mekanik sağlam ama devrimci değil. Dekorasyon katmanı progression hissi veriyor.",
      monetizationModel: "Freemium — IAP + reklamlı ödüller",
      monetizationIap: "Coin paketleri, ekstra hamle, booster paketleri, özel teklifler",
      monetizationAds: "Opsiyonel reklam izleyerek ödül kazanma — agresif değil",
      monetizationBattlePass: "Team Battle ve King's League sezonluk etkinlikler",
      monetizationRating: "8",
      monetizationNotes: "Monetization dengeli. Oyuncu zorlandığında satın alma teşviki var ama agresif değil. Reklam opsiyonel tutulmuş.",
      retentionRewards: "Günlük coin bonusu, ücretsiz spin, takım ödülleri",
      retentionStreak: "Günlük giriş ödülleri ve ardışık oynama bonusları",
      retentionRating: "8",
      retentionNotes: "Günlük ödüller, takım etkinlikleri ve sürekli yeni seviyeler retention sağlıyor. Dekorasyon ilerleme hissi güçlü.",
      uxRating: "9",
      uxMenu: "Ana menü sade ve temiz. Tüm özellikler kolayca erişilebilir. Dekorasyon ekranına geçiş akıcı.",
      uxButtons: "Butonlar büyük ve dokunmatik dostu. Renk kodlaması tutarlı.",
      uxHud: "Oyun içi HUD minimal — hamle sayısı, hedef, skor. Dikkat dağıtmıyor.",
      uxNotes: "UI son derece temiz ve polished. Animasyonlar akıcı, feedback tatmin edici.",
      metaSystems: "Krallık dekorasyonu, takım sistemi, King's League, koleksiyon albümü",
      metaLongTerm: "Dekorasyon ilerlemesi sonsuz içerik sağlıyor. Takım etkinlikleri sosyal bağ oluşturuyor.",
      metaRating: "7",
      metaNotes: "Dekorasyon sistemi güçlü meta progression. Ancak endgame derinliği sınırlı.",
      overallBestFeature: "Görsel kalite ve dekorasyon meta sistemi",
      overallWorstFeature: "Puzzle mekaniği diğer match-3 oyunlardan farksız",
      overallTargetAudience: "Casual oyuncular, 25-45 yaş, çoğunlukla kadın demografisi",
      overallLearnings: "Güçlü bir meta progression (dekorasyon) sıradan bir core loop'u bile çekici kılabiliyor.",
    },
    {
      gameId: inserted[2].id, // PUBG Mobile
      userId: user.id,
      ftueFirstImpression: "Oyun büyüklüğü nedeniyle uzun indirme süresi. Giriş ekranı etkileyici ama karmaşık.",
      ftueOnboardingType: "Bot lobby — ilk maçlar kolaylaştırılmış AI rakiplerle",
      ftueDuration: "15-20 dakika (ilk maç)",
      ftueRating: "6",
      ftueNotes: "FTUE zayıf nokta. Kontroller karmaşık, öğrenme eğrisi dik. Bot lobby güven veriyor ama oyuncu fark etmeyebilir.",
      coreLoopDefinition: "Lobi → uçaktan atla → loot topla → hayatta kal → savaş → chicken dinner veya elim → tekrar",
      coreLoopSessionLength: "20-30 dakika (tek maç)",
      coreLoopRating: "7",
      coreLoopNotes: "Battle royale formatı heyecan verici ama uzun oturum süresi mobil için dezavantaj.",
      monetizationModel: "Freemium — kozmetik IAP + Royale Pass",
      monetizationIap: "UC (Unknown Cash) paketleri, skin kutuları, araç skinleri, silah skinleri",
      monetizationAds: "Reklam yok — tamamen IAP odaklı",
      monetizationBattlePass: "Royale Pass: sezonluk premium ödüller, skin seti, emote, çerçeve",
      monetizationRating: "7",
      monetizationNotes: "Kozmetik odaklı, P2W yok. Royale Pass iyi değer sunuyor. Gacha mekanizması (kasa açma) bazı oyuncular için sorunlu.",
      retentionRewards: "Günlük login ödülleri, haftalık görevler, RP mission ödülleri",
      retentionStreak: "Günlük görevler, haftalık görevler, sezon görevleri zinciri",
      retentionRating: "6",
      retentionNotes: "Günlük görevler ve Royale Pass ilerleme sağlıyor. Arkadaşlarla oynama güçlü retention mekanizması.",
      uxRating: "5",
      uxMenu: "Ana menü çok kalabalık — event banner'ları, shop, mode seçimi üst üste. Yeni oyuncu kaybolabilir.",
      uxButtons: "Butonlar küçük ve yoğun. Ayarlar menüsü çok katmanlı.",
      uxHud: "Oyun içi HUD bilgi yoğun ama özelleştirilebilir. Minimap, silah, can, zırh, takım bilgisi.",
      uxNotes: "Menüler çok karmaşık. Yeni oyuncu için overwhelming. Kontrol özelleştirmesi güçlü ama başlangıçta kafa karıştırıcı.",
      metaSystems: "Ranking sistemi, achievement koleksiyonu, season pass, companion sistemi, clan",
      metaLongTerm: "Tier yükselme (Bronze→Conqueror) uzun vadeli hedef. Ancak içerik tekrarı yüksek.",
      metaRating: "6",
      metaNotes: "Ranking sistemi motivasyon kaynağı ama endgame'de içerik çeşitliliği düşük.",
      overallBestFeature: "PC kalitesinde battle royale deneyimi mobilde",
      overallWorstFeature: "UI karmaşıklığı ve uzun maç süreleri",
      overallTargetAudience: "Hardcore oyuncular, shooter severler, 16-30 yaş",
      overallLearnings: "Mobilde uzun oturum süreleri riskli. UI basitliği kritik — PUBG'nin menü karmaşıklığı yeni oyuncu kaybettirebilir.",
    },
    {
      gameId: inserted[3].id, // Idle Heroes
      userId: user.id,
      ftueFirstImpression: "Parlak ve renkli açılış ekranı. Hemen bir kahraman veriliyor ve otomatik savaş başlıyor.",
      ftueOnboardingType: "Guided auto-play — sistem oyuncuyu adım adım yönlendiriyor, ilk savaşlar otomatik",
      ftueDuration: "5-10 dakika",
      ftueFrictionPoints: "Çok fazla UI elementi ve menü hemen açılıyor. Bilgi bombardımanı yaratıyor.",
      ftuePermissionTiming: "Bildirim izni 2. gün push ile isteniyor",
      ftueRating: "5",
      ftueNotes: "FTUE hızlı ama ezici. Oyuncu neyi neden yaptığını anlamadan ilerliyor. Auto-battle konsepti net ama menü karmaşıklığı kafa karıştırıcı.",
      coreLoopDefinition: "Kahraman topla → takım kur → idle gelir biriktir → savaşa gir → kahraman güçlendir → tekrar",
      coreLoopSessionLength: "2-5 dakika (aktif) + sınırsız idle",
      coreLoopMasteryCurve: "Düz bir eğri — stratejik derinlik sınırlı, güç odaklı ilerleme (power creep).",
      coreLoopVariety: "6 faktör: kahraman, teçhizat, evcil hayvan, guild, abyss, tower. Çeşitlilik var ama hepsi stat artışına bağlı.",
      coreLoopRating: "5",
      coreLoopNotes: "Idle mekaniği çekici: oyun kapalıyken gelir birikiyor. Ama aktif oynanış tekrarcı, stratejik derinlik az.",
      monetizationModel: "Freemium — ağır IAP + VIP sistemi + gacha",
      monetizationIap: "Gem paketleri, kahraman kutuları, özel etkinlik paketleri, ayı kart, aylık kart",
      monetizationAds: "Reklam izleyerek az miktarda gem/kaynak",
      monetizationVip: "VIP 1-13 seviyeleri: toplam harcamaya göre kalıcı avantajlar. P2W unsuru belirgin.",
      monetizationRating: "4",
      monetizationNotes: "Çok agresif monetization. VIP sistemi P2W'yi normalleştiriyor. Gacha oranları düşük, pity sistemi geç devreye giriyor.",
      retentionRewards: "Idle gelir, günlük görevler, arena ödülleri, tavern quests",
      retentionStreak: "7 günlük login ödül takvimi, aylık check-in",
      retentionFomo: "Sınırlı süreli etkinlikler, limited edition kahramanlar, geri sayım banner'ları",
      retentionRating: "6",
      retentionNotes: "Idle gelir geri dönmeye teşvik ediyor. FOMO mekanikleri agresif. Guild sistemi sosyal bağ oluşturuyor ama cezalandırıcı.",
      uxRating: "4",
      uxMenu: "Ana ekran event banner'ları ile dolu. 15+ farklı mod ve menü var.",
      uxButtons: "Butonlar küçük ve yoğun. Ekran kalabalığı dikkat dağıtıcı.",
      uxHud: "Savaş ekranı basit ama otomatik — oyuncu izliyor.",
      uxNotes: "UI son derece karmaşık. Yeni oyuncu için menü labirenti. Feature bloat belirgin.",
      metaSystems: "Void, Abyss, Tower of Oblivion, Guild War, arena, celestial island",
      metaLongTerm: "Kahraman koleksiyonu ve faction bonusları uzun vadeli hedef. Ama power creep sürekli reset hissi veriyor.",
      metaRating: "5",
      metaNotes: "Meta sistemler çok fazla ama çoğu stat check. Gerçek stratejik çeşitlilik sınırlı.",
      techRating: "6",
      techNotes: "Grafik kalitesi orta. Animasyonlar tekrarcı. Batarya tüketimi yüksek (arka plan idle).",
      overallBestFeature: "Idle gelir mekanizması — oyun kapalıyken bile ilerleme",
      overallWorstFeature: "Agresif monetization ve VIP sistemi, UI karmaşıklığı",
      overallUniqueMechanic: "Idle gelir + gacha kahraman koleksiyonu hybrid — zaman bazlı ilerleme",
      overallTargetAudience: "Casual-midcore RPG severler, koleksiyoncular, 20-40 yaş",
      overallLearnings: "Idle mekanik retention için güçlü ama agresif monetization uzun vadede oyuncu kaybettirir. Feature bloat UX'i ciddi şekilde bozar.",
    },
    {
      gameId: inserted[4].id, // Monopoly GO!
      userId: user.id,
      ftueFirstImpression: "Nostaljik Monopoly teması anında tanıdıklık hissi veriyor. Renkli, enerjik açılış.",
      ftueOnboardingType: "Guided dice roll — ilk turlar yönlendirilmiş, temel mekanikler adım adım",
      ftueDuration: "3-5 dakika",
      ftueFrictionPoints: "Zar atma mekanizması hemen anlaşılıyor ama mini-game çeşitliliği başta kafa karıştırabilir.",
      ftueRating: "7",
      ftueNotes: "FTUE iyi akıyor. Monopoly nostalji faktörü öğrenme eşiğini düşürüyor. Hemen ödüller vererek motivasyon sağlıyor.",
      coreLoopDefinition: "Zar at → tahtada ilerle → para/kalkan/saldırı → sticker topla → albüm tamamla → yeni tahta aç",
      coreLoopSessionLength: "5-10 dakika (zarlar bitene kadar)",
      coreLoopMasteryCurve: "Çok düz — strateji neredeyse yok, şans bazlı ilerleme.",
      coreLoopVariety: "Zar atma, banka soygunu, saldırı/kalkan, sticker ticareti, turnuva. Çeşitlilik var ama hepsi RNG.",
      coreLoopRating: "6",
      coreLoopNotes: "Core loop basit ve çekici ama derinlik eksik. Tamamen şans bazlı olması stratejik oyuncuları uzaklaştırabilir.",
      monetizationModel: "Freemium — ağır IAP + zar satın alma + event paketleri",
      monetizationIap: "Zar paketleri, sticker paketleri, event özel teklifleri, VIP paketleri",
      monetizationAds: "Reklam izleyerek ücretsiz zar kazanma",
      monetizationRating: "5",
      monetizationNotes: "Monetization agresif. Zar ekonomisi yapay kıtlık yaratıyor. Event'ler sürekli harcamaya teşvik ediyor. Başarılı UA stratejisi geliri yüksek tutuyor.",
      retentionRewards: "Günlük ücretsiz zarlar, arkadaş ödülleri, sticker ticareti ödülleri",
      retentionStreak: "Günlük login zarları, ardışık gün bonusları",
      retentionSocial: "Arkadaş saldırı/yardım sistemi, sticker ticareti — güçlü sosyal mekanik",
      retentionFomo: "Sınırlı süreli etkinlikler, partner etkinlikleri (film/marka collab), topluluk hedefleri",
      retentionRating: "7",
      retentionNotes: "Sosyal mekanikler çok güçlü. Sticker ticareti viral loop yaratıyor. FOMO event'ler geri dönüş sağlıyor.",
      uxRating: "7",
      uxMenu: "Ana ekran sade. Tahta görünümü tanıdık Monopoly estetiği.",
      uxButtons: "Büyük, dokunmatik dostu butonlar. Casual kitle için uygun.",
      uxHud: "Zar sayısı, para, kalkan durumu üstte. Sade ve okunaklı.",
      uxNotes: "UI casual kitle için iyi optimize edilmiş. Monopoly teması tanıdıklık avantajı sağlıyor. Event banner'ları biraz kalabalık.",
      metaSystems: "Sticker albüm koleksiyonu, tahta ilerleme, partner etkinlikleri, turnuvalar",
      metaLongTerm: "Albüm tamamlama uzun vadeli hedef. Her yeni set motivasyon yeniliyor ama sonsuz grind hissi verebilir.",
      metaRating: "6",
      metaNotes: "Sticker sistemi akıllı meta mekanik. Ticaret sosyal bağ oluşturuyor. Ama endgame tekrarcı.",
      techRating: "7",
      techNotes: "Grafik kalitesi iyi, animasyonlar eğlenceli. Uygulama boyutu makul. Bazı event'lerde performans düşüşü.",
      overallBestFeature: "Nostaljik Monopoly markası + sticker ticareti sosyal mekanizması",
      overallWorstFeature: "Tamamen şans bazlı core loop, stratejik derinlik yok",
      overallUniqueMechanic: "Board game + idle hybrid — nostaljik IP üzerinde casual sosyal mekanik",
      overallTargetAudience: "Casual oyuncular, Monopoly hayranları, sosyal oyuncular, 18-50 yaş",
      overallLearnings: "Güçlü IP (marka) kullanımı UA maliyetini düşürür. Sosyal mekanikler (sticker ticareti) organik büyüme sağlar. Ama şans bazlı loop hardcore oyuncuyu tutmaz.",
    },
  ];

  await db.insert(analyses).values(templateAnalyses);

  // Template AI analyses for first 3 games
  const templateAiAnalyses = [
    {
      gameId: inserted[0].id, // Clash Royale
      userId: user.id,
      executiveSummary: "Clash Royale, mobil oyun endüstrisinin en başarılı örneklerinden biri. Gerçek zamanlı PvP, kısa oturum süreleri ve derin strateji kombinasyonu. Analiz kalitesi iyi seviyede, ancak monetization ve retention mekaniklerinin derinlemesine incelenmesi gerekiyor.",
      categoryScores: {
        ftue: { gameScore: 8, analysisQuality: 7, comment: "FTUE analizi iyi yapılmış. Tutorial flow'un detayları doğru gözlemlenmiş." },
        coreLoop: { gameScore: 9, analysisQuality: 8, comment: "Core loop tanımı mükemmel. Elixir yönetimi ve deck building derinliği doğru tespit edilmiş." },
        monetization: { gameScore: 7, analysisQuality: 6, comment: "Monetization modeli tanımlanmış ama derinlik eksik. P2W vs P2P tartışması yapılmalıydı." },
        retention: { gameScore: 8, analysisQuality: 7, comment: "Klan sistemi ve ladder mekanikleri doğru tespit edilmiş." },
        uxui: { gameScore: 8, analysisQuality: 6, comment: "UI değerlendirmesi yüzeysel kalmış. Battle UI'daki bilgi hiyerarşisi analiz edilmeliydi." },
        metaGame: { gameScore: 9, analysisQuality: 8, comment: "Meta sistem analizi kapsamlı. Klan savaşlarının sosyal etkisi iyi gözlemlenmiş." },
        technical: { gameScore: 8, analysisQuality: 5, comment: "Teknik analiz eksik. Netcode, sunucu altyapısı ve matchmaking sistemi incelenmeliydi." },
      },
      observationLevel: "intermediate",
      strengths: ["Core loop analizi derinlikli", "Meta sistem gözlemleri kapsamlı", "Rekabetçi dinamikler iyi anlaşılmış"],
      weaknesses: ["Monetization analizi yüzeysel", "Teknik altyapı değerlendirilmemiş", "Rakip karşılaştırması eksik"],
    },
    {
      gameId: inserted[1].id, // Royal Match
      userId: user.id,
      executiveSummary: "Royal Match, match-3 pazarında Dream Games'in büyük başarısı. Görsel kalite ve meta progression (dekorasyon) ile fark yaratıyor. Analiz temel noktaları yakalamış ancak pazarlama stratejisi ve UA yaklaşımı eksik.",
      categoryScores: {
        ftue: { gameScore: 9, analysisQuality: 8, comment: "FTUE analizi detaylı ve doğru. Kral karakterinin empati yaratma etkisi güzel tespit." },
        coreLoop: { gameScore: 8, analysisQuality: 7, comment: "Match-3 mekaniğinin standart olduğu doğru gözlem. Dekorasyon katmanının farkı anlaşılmış." },
        monetization: { gameScore: 8, analysisQuality: 6, comment: "Monetization modeli tanımlanmış ama conversion funnel ve LTV analizi yapılmalıydı." },
        retention: { gameScore: 8, analysisQuality: 6, comment: "Retention mekanikleri listelenmiş ama derinlik eksik." },
        uxui: { gameScore: 9, analysisQuality: 8, comment: "UI/UX analizi güçlü. Animasyon kalitesi ve feedback döngüsü doğru gözlemlenmiş." },
        metaGame: { gameScore: 7, analysisQuality: 6, comment: "Dekorasyon sistemi değerlendirilmiş ama sosyal mekanikler atlanmış." },
        technical: { gameScore: 8, analysisQuality: 5, comment: "Teknik analiz eksik. Performans optimizasyonu ve cross-platform deneyim incelenmeliydi." },
      },
      observationLevel: "intermediate",
      strengths: ["FTUE gözlemleri keskin", "UI/UX analizi detaylı", "Meta progression farkı anlaşılmış"],
      weaknesses: ["Monetization derinliği yetersiz", "Teknik analiz eksik", "Pazar pozisyonu analizi yok"],
    },
    {
      gameId: inserted[2].id, // PUBG Mobile
      userId: user.id,
      executiveSummary: "PUBG Mobile, battle royale türünün mobil öncüsü. PC deneyimini başarıyla mobilde sunuyor ama UI karmaşıklığı ve uzun oturum süreleri zayıf noktaları. Analiz ehrli ve eleştirel, bu PM adayı için olumlu bir işaret.",
      categoryScores: {
        ftue: { gameScore: 6, analysisQuality: 7, comment: "FTUE sorunları doğru tespit edilmiş. Bot lobby yaklaşımı ve kontrol karmaşıklığı iyi analiz edilmiş." },
        coreLoop: { gameScore: 7, analysisQuality: 6, comment: "Battle royale döngüsü tanımlanmış ama session length'in retention etkisi derinleştirilmeliydi." },
        monetization: { gameScore: 7, analysisQuality: 6, comment: "Kozmetik odaklı model doğru ama Royale Pass'in conversion metrikleri tartışılmalıydı." },
        retention: { gameScore: 6, analysisQuality: 6, comment: "Sosyal oynanış retention etkisi doğru tespit ama mekanik detay eksik." },
        uxui: { gameScore: 5, analysisQuality: 7, comment: "UI eleştirisi cesur ve doğru. Menü karmaşıklığının yeni oyuncu kaybına etkisi iyi gözlem." },
        metaGame: { gameScore: 6, analysisQuality: 5, comment: "Meta sistem analizi yüzeysel. Ranking, achievement ve koleksiyon sistemleri incelenmeliydi." },
        technical: { gameScore: 7, analysisQuality: 5, comment: "Teknik analiz eksik. Grafik ayarları, ping/latency ve cihaz optimizasyonu kritik konular." },
      },
      observationLevel: "beginner",
      strengths: ["UX eleştirisi cesur ve doğru", "FTUE sorunları iyi tespit edilmiş", "Genel değerlendirmeler tutarlı"],
      weaknesses: ["Analiz genel olarak yüzeysel", "Teknik derinlik çok yetersiz", "Metrik ve veri odaklı yaklaşım eksik"],
    },
    {
      gameId: inserted[3].id, // Idle Heroes
      userId: user.id,
      executiveSummary: "Idle Heroes, idle RPG türünün erken öncülerinden. Idle gelir mekanizması çekici ama agresif monetization ve VIP sistemi ciddi P2W sorunları yaratıyor. Analiz monetization eleştirisi konusunda cesur ve doğru, bu PM adayı için önemli bir gözlem.",
      categoryScores: {
        ftue: { gameScore: 5, analysisQuality: 7, comment: "FTUE sorunları doğru tespit edilmiş. Bilgi bombardımanı ve menü karmaşıklığı iyi gözlemlenmiş." },
        coreLoop: { gameScore: 5, analysisQuality: 6, comment: "Idle mekaniğin çekiciliği ve sınırları doğru analiz edilmiş. Power creep tespiti yerinde." },
        monetization: { gameScore: 4, analysisQuality: 8, comment: "Monetization analizi çok güçlü. VIP sistemi ve gacha eleştirisi cesur ve doğru. P2W tespiti önemli." },
        retention: { gameScore: 6, analysisQuality: 7, comment: "FOMO mekanikleri ve idle gelir retention etkisi doğru tespit edilmiş." },
        uxui: { gameScore: 4, analysisQuality: 7, comment: "Feature bloat ve UI karmaşıklığı eleştirisi çok yerinde. Menü labirenti iyi ifade edilmiş." },
        metaGame: { gameScore: 5, analysisQuality: 5, comment: "Meta sistemler listelenmiş ama stratejik derinlik analizi yapılabilirdi." },
        technical: { gameScore: 6, analysisQuality: 5, comment: "Teknik analiz minimal. Arka plan idle'ın batarya etkisi not edilmiş ama derinlik eksik." },
      },
      observationLevel: "intermediate",
      strengths: ["Monetization eleştirisi cesur ve detaylı", "Feature bloat UX analizi güçlü", "Idle mekaniğin artı/eksileri dengeli değerlendirilmiş"],
      weaknesses: ["Meta sistem analizi yüzeysel", "Teknik analiz eksik", "Rakip idle oyunlarla karşılaştırma yapılmamış"],
    },
    {
      gameId: inserted[4].id, // Monopoly GO!
      userId: user.id,
      executiveSummary: "Monopoly GO!, güçlü IP kullanımı ve sosyal mekaniklerle casual pazarda büyük başarı yakalamış. Sticker ticareti viral loop yaratıyor. Analiz sosyal mekaniklerin gücünü iyi yakalamış ancak UA stratejisi ve pazar analizi eksik.",
      categoryScores: {
        ftue: { gameScore: 7, analysisQuality: 7, comment: "Nostalji faktörünün öğrenme eşiğini düşürmesi güzel tespit. FTUE akışı doğru analiz edilmiş." },
        coreLoop: { gameScore: 6, analysisQuality: 7, comment: "Şans bazlı loop'un sınırları doğru tespit edilmiş. Stratejik derinlik eksikliği yerinde eleştiri." },
        monetization: { gameScore: 5, analysisQuality: 7, comment: "Zar ekonomisi kıtlık analizi doğru. Event bazlı harcama teşviki iyi gözlemlenmiş." },
        retention: { gameScore: 7, analysisQuality: 8, comment: "Sosyal mekaniklerin retention etkisi mükemmel analiz edilmiş. Sticker ticareti viral loop tespiti çok değerli." },
        uxui: { gameScore: 7, analysisQuality: 6, comment: "UI analizi yeterli. Monopoly temasının tanıdıklık avantajı doğru tespit." },
        metaGame: { gameScore: 6, analysisQuality: 6, comment: "Sticker sistemi değerlendirilmiş ama endgame analizi yapılabilirdi." },
        technical: { gameScore: 7, analysisQuality: 5, comment: "Teknik analiz minimal. Performans ve uygulama boyutu notları var ama derinlik eksik." },
      },
      observationLevel: "intermediate",
      strengths: ["Sosyal mekanik analizi mükemmel", "IP kullanımının UA etkisi iyi anlaşılmış", "Monetization eleştirisi dengeli"],
      weaknesses: ["Pazar pozisyonu analizi eksik", "Teknik derinlik yetersiz", "Casual vs midcore kitle farkı tartışılmamış"],
    },
  ];

  await db.insert(aiAnalyses).values(templateAiAnalyses);

  return NextResponse.json({
    message: `${inserted.length} seed oyun + 5 analiz + 5 AI analiz eklendi`,
    games: inserted.map((g) => ({ id: g.id, title: g.title })),
  });
}
